name: 🎉 Deploy in PROD environment!

on:
  release:
    types: [ created ]

env:
  HOST: ${{ secrets.REMOTE_HOST }}
  USERNAME: ${{ secrets.REMOTE_USER }}
  SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

jobs:
  deploy:
    name: Deploy with SSH
    runs-on: ubuntu-latest
    steps:
    - name: Pull and run project
      uses: appleboy/ssh-action@v0.1.5
      env:
        LOCAL: ${{ github.event.repository.name }}
        REMOTE: ${{ github.event.repository.html_url }}.git
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      with:
        host: $HOST
        username: $USERNAME
        key: $SSH_KEY
        envs: LOCAL,REMOTE,BOT_TOKEN
        script_stop: true
        script: |
          if [ -d $LOCAL/.git ]; then git -C $LOCAL reset --hard HEAD~; git -C $LOCAL pull; else rm -rf $LOCAL; git clone $REMOTE; fi
          chmod +x -R $LOCAL/scripts
          $LOCAL/scripts/build.sh ~/$LOCAL
          export MY_TOKEN=$BOT_TOKEN
          $LOCAL/scripts/run.sh
